# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sonia.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 549)
        MainWindow.setMinimumSize(QtCore.QSize(800, 549))
        MainWindow.setMaximumSize(QtCore.QSize(800, 549))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 141, 131))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 231, 100))
        self.label_2.setPixmap(QtGui.QPixmap(":/mon_dossier/logo1.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, -20, 181, 221))
        self.label_3.setPixmap(QtGui.QPixmap(":/mon_dossier/logo2.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 120, 461, 81))
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 210, 601, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.input_valeur = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.input_valeur.setMaximum(9900000000000000.0)
        self.input_valeur.setObjectName("input_valeur")
        self.horizontalLayout_2.addWidget(self.input_valeur)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_g = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radio_g.setChecked(True)
        self.radio_g.setObjectName("radio_g")
        self.horizontalLayout.addWidget(self.radio_g)
        self.radio_kg = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radio_kg.setObjectName("radio_kg")
        self.horizontalLayout.addWidget(self.radio_kg)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.btn_calculer = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_calculer.setStyleSheet("background-color: rgb(228, 242, 231);")
        self.btn_calculer.setObjectName("btn_calculer")
        self.horizontalLayout_2.addWidget(self.btn_calculer)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 270, 601, 221))
        self.groupBox.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 16, 581, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.text_masse_eau_distille = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_eau_distille.setObjectName("text_masse_eau_distille")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_masse_eau_distille)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.text_masse_beurre_cacao = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_beurre_cacao.setObjectName("text_masse_beurre_cacao")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_masse_beurre_cacao)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.text_masse_huile_cactus = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_huile_cactus.setObjectName("text_masse_huile_cactus")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.text_masse_huile_cactus)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.text_masse_cire_emulsifiante = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_cire_emulsifiante.setObjectName("text_masse_cire_emulsifiante")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_masse_cire_emulsifiante)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.text_masse_glycerine = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_glycerine.setObjectName("text_masse_glycerine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text_masse_glycerine)
        self.text_masse_vitamine_e = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_vitamine_e.setObjectName("text_masse_vitamine_e")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.text_masse_vitamine_e)
        self.text_masse_cosgard = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_cosgard.setObjectName("text_masse_cosgard")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.text_masse_cosgard)
        self.text_masse_arome_cacao = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_arome_cacao.setObjectName("text_masse_arome_cacao")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.text_masse_arome_cacao)
        self.text_masse_acide_citrique = QtWidgets.QLabel(self.formLayoutWidget)
        self.text_masse_acide_citrique.setObjectName("text_masse_acide_citrique")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.text_masse_acide_citrique)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_calculer.clicked.connect(self.calculer)
    
    def calculer(self):
        masse_creme = self.input_valeur.value()
        masse_eau_distille=(masse_creme*58)/100
        def convert(value):
            uniter=" g"
            if self.radio_kg.isChecked():
                value*=1000
            return str(value)+ uniter
        self.text_masse_eau_distille.setText(convert(masse_eau_distille))
        
        masse_beurre_cacao = (masse_creme*20)/100
        self.text_masse_beurre_cacao.setText(convert(masse_beurre_cacao))

        masse_huile_cactus = (masse_creme*6)/100
        self.text_masse_huile_cactus.setText(convert(masse_huile_cactus))

        masse_cire_emulsifiante = (masse_creme*5.5)/100
        self.text_masse_cire_emulsifiante.setText(convert(masse_cire_emulsifiante))

        masse_glycerine = (masse_creme*4)/100
        self.text_masse_glycerine.setText(convert(masse_glycerine))

        masse_vitamineE = (masse_creme*0.32)/100
        self.text_masse_vitamine_e.setText(convert(masse_vitamineE))

        masse_cosgard = (masse_creme*0.6)/100 
        self.text_masse_cosgard.setText(convert(masse_cosgard))

        masse_arome_cacao = (masse_creme*2.5)/100 
        self.text_masse_arome_cacao.setText(convert(masse_arome_cacao))
        
        masse_acide_citrique = (masse_creme*0.04)/100 
        self.text_masse_acide_citrique.setText(convert(masse_acide_citrique))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/mon_dossier/logo-removebg-preview.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/mon_dossier/logo1-removebg-preview.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/mon_dossier/logo2-removebg-preview.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial Black,sans-serif\'; font-size:20pt; color:#17365d;\">CREME ANTIRIDE A BASE DE</span></p><p align=\"center\"><span style=\" font-family:\'Arial Black,sans-serif\'; font-size:20pt; color:#17365d;\">BEURRE DE CACAO</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Entrer la quantité de crème à préparer : </span></p></body></html>"))
        self.radio_g.setText(_translate("MainWindow", "g"))
        self.radio_kg.setText(_translate("MainWindow", "Kg"))
        self.btn_calculer.setText(_translate("MainWindow", "Calculer"))
        self.groupBox.setTitle(_translate("MainWindow", "Resultats : "))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de l\'eau disrillé : </span></p></body></html>"))
        self.text_masse_eau_distille.setText(_translate("MainWindow", "<html><head/><body><p>0</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de beurre de cacao : </span></p></body></html>"))
        self.text_masse_beurre_cacao.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de l\'huile de cactus : </span></p></body></html>"))
        self.text_masse_huile_cactus.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de cire d\'emulsifiante : </span></p></body></html>"))
        self.text_masse_cire_emulsifiante.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de glycerine : </span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de vitamine E :</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse de cosgard : </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse d\'arome de cacao : </span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Masse d\'acide citrique : </span></p></body></html>"))
        self.text_masse_glycerine.setText(_translate("MainWindow", "0"))
        self.text_masse_vitamine_e.setText(_translate("MainWindow", "0"))
        self.text_masse_cosgard.setText(_translate("MainWindow", "0"))
        self.text_masse_arome_cacao.setText(_translate("MainWindow", "0"))
        self.text_masse_acide_citrique.setText(_translate("MainWindow", "0"))
import fichier_source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
